### ISSUE TITLE
Alineación de elementos en "Hero Section"

### ISSUE THREAD

**Issue by AndrewAlva** [fdanielsa/Franspost-maquetacion#1]
Dani! Para el problema de alineamiento de la imagen con el texto (y de bloques en general, como "divs"); necesitas utilizar las propiedades "float" o "display" en ambos elementos; dependiendo de lo que quieras lograr puedes utilizar "float: left o right" o "display: inline-block"; en este caso un display inline block funcionaría mejor, float te pide unas lineas extras para calcular el alto de los objetos y recuerda que entre menos lineas escribamos es mejor, entonces display inline block nos funciona mejor aquí.

El único detalle es que HTML tiene un pedo con alinear objetos que suman 100% porque dibuja espacio en blanco sin que se lo indiques. Para eliminar esos espacios blancos tienes que agregarle una propiedad extra al padre, esta propiedad es "white-space: nowrap".

La tercera opción es utilizar "flexbox", esta propiedad es más reciente pero es soportada por la mayoría de los navegadores desde hace varios años, internet explorer es el que llega a tener problemas, (aquí más info al respecto: https://caniuse.com/#feat=flexbox) 

Flexbox ya tiene resuelto ese pedo de los espacios en blanco y es sencillo de usar, aquí en lugar de ponerle a los elementos que quieres alineados "float" o "display", con flexbox le pones la propiedad al padre "display: flex" y te los alinea, respetando el ancho que les des con "width". 

Para este ejercicio utiliza flexbox para que te vayas familiarizando con él. Te va a quedar así cuando se lo pongas:

![captura de pantalla 2018-10-05 a las 14 47 07](https://user-images.githubusercontent.com/10885120/46556910-afda0b00-c8ad-11e8-9f3a-8fb17cd7a20d.png)

**Comment by fdanielsa** [comment]
Andrew!!
ya hice algunos cambios en esta sección, subo el repo.

**Comment by AndrewAlva** [comment]
Dani! Había estado super ocupado, pero ya ando revisando el código.

En cuanto a este tema ya vi que estás utilizando "display: flex", solamente haría falta agregar "prefijos" para aumentar la compatibilidad del código con los navegadores no tan recientes; esta página te va a servir de guía para identificar qué propiedades necesitan de "prefijos" y cúando usarlos:

http://shouldiprefix.com/

También recuerda quitar las propiedades que estabas utilizando anteriormente para alinear, como los "floats"; siempre ten cuidado con estas cosas, ten en mente lo que estabas intentando para que cuando encuentres la solución quites código que ya no está haciendo algo y que puede llegar a causar errores:

![captura de pantalla 2018-10-11 a las 17 23 35](https://user-images.githubusercontent.com/10885120/46837344-9b4cb580-cd7a-11e8-999a-ccc022053b30.png)
